name: horizontal_calender
description: horizontal callender
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  badges: ^3.1.2
  flutter:
    sdk: flutter
  intl: ^0.19.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
